"""Narration text builder + TTS bytes.

The browser fetches ``/api/narration?q=<place>&auto=1`` (or with
explicit ``&text=...``) and mixes the resulting audio into MediaRecorder
via Web Audio. No ffmpeg merge needed — the recording lays the audio
track directly into the .mp4 container alongside H.264 video.

Narration length is calibrated to video duration when ``duration_seconds``
is given. If ANTHROPIC_API_KEY or OPENAI_API_KEY is set, the text is
generated by the matching LLM for richer, location-aware copy; the
template builder is used as fallback.
"""

from __future__ import annotations

import json
import os
import urllib.request
from typing import Any

from . import live as live_mod


# Turkish ~110 wpm, German/English ~130 wpm (conservative for TTS clarity)
_WPM = {"tr": 110, "de": 130, "en": 130}


def auto_text_for(
    place: str,
    *,
    lang: str = "tr",
    duration_seconds: float | None = None,
    context: dict[str, Any] | None = None,
) -> str:
    """Generate a narration script for *place*.

    Parameters
    ----------
    place:
        Location name or description.
    lang:
        Language code — ``"tr"``, ``"de"``, or ``"en"``.
    duration_seconds:
        When set, the returned text is calibrated to fill this many seconds
        at natural TTS speed.
    context:
        Optional pre-fetched live bundle so we skip a second network call.
    """
    # 1. LLM narration (richer, context-aware)
    llm = _llm_narration(place, lang=lang, duration_seconds=duration_seconds, context=context)
    if llm:
        return llm

    # 2. Template narration (always works offline)
    try:
        bundle = context or live_mod.snapshot(place, marine=False, radius_km=50.0)
    except ValueError:
        return _fallback(place, lang, duration_seconds)
    return _compose(bundle, lang=lang, duration_seconds=duration_seconds)


# ---------------------------------------------------------------------------
# LLM narration — stdlib urllib only, no new pip dependency
# ---------------------------------------------------------------------------

def _llm_narration(
    place: str,
    *,
    lang: str,
    duration_seconds: float | None,
    context: dict[str, Any] | None,
) -> str | None:
    api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if api_key:
        return _anthropic_narration(place, lang=lang, duration_seconds=duration_seconds, context=context, api_key=api_key)
    api_key = os.environ.get("OPENAI_API_KEY", "").strip()
    if api_key:
        return _openai_narration(place, lang=lang, duration_seconds=duration_seconds, context=context, api_key=api_key)
    return None


def _build_llm_prompt(
    place: str,
    *,
    lang: str,
    duration_seconds: float | None,
    context: dict[str, Any] | None,
) -> str:
    lang_names = {"tr": "Turkish", "de": "German", "en": "English"}
    lang_name = lang_names.get(lang[:2], "English")
    wpm = _WPM.get(lang[:2], 130)
    if duration_seconds:
        target = int(duration_seconds * wpm / 60)
        length_instr = f"exactly {target} words (for a {int(duration_seconds)}-second video at {wpm} wpm)"
    else:
        length_instr = "about 10 seconds when read aloud"

    ctx_lines: list[str] = []
    if context:
        w = context.get("weather") or {}
        if w.get("temperature_c") is not None:
            ctx_lines.append(f"temperature {w['temperature_c']}°C")
        if w.get("wind_kmh") is not None:
            ctx_lines.append(f"wind {w['wind_kmh']} km/h")
        fires = context.get("wildfires_nearby") or 0
        if fires:
            ctx_lines.append(f"{fires} active fire hotspots nearby")
        cams = context.get("cameras") or []
        if cams:
            ctx_lines.append(f"live camera: {cams[0].get('name', '')}")
        hotspot = context.get("hotspot")
        if hotspot:
            frp = hotspot.get("frp")
            ctx_lines.append(f"fire radiative power {frp} MW" if frp else "active fire detected")
    ctx_block = (". ".join(ctx_lines) + ".") if ctx_lines else ""

    return (
        f"You are the voice of CelebiPlug, a cinematic drone system.\n"
        f"Write a drone narration in {lang_name} for: {place}.\n"
        f"{f'Real-time data: {ctx_block} ' if ctx_block else ''}"
        f"Length: {length_instr}.\n"
        f"Style: cinematic, geographic, evocative. No filler phrases.\n"
        f"Begin with the drone name 'Çelebi'. Return ONLY the narration text."
    )


def _anthropic_narration(
    place: str,
    *,
    lang: str,
    duration_seconds: float | None,
    context: dict[str, Any] | None,
    api_key: str,
) -> str | None:
    try:
        prompt = _build_llm_prompt(place, lang=lang, duration_seconds=duration_seconds, context=context)
        payload = json.dumps({
            "model": "claude-haiku-4-5-20251001",
            "max_tokens": 400,
            "messages": [{"role": "user", "content": prompt}],
        }).encode()
        req = urllib.request.Request(
            "https://api.anthropic.com/v1/messages",
            data=payload,
            headers={
                "Content-Type": "application/json",
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=12) as resp:
            result = json.loads(resp.read().decode())
        for block in result.get("content") or []:
            if block.get("type") == "text":
                return block["text"].strip()
    except Exception:  # noqa: BLE001
        pass
    return None


def _openai_narration(
    place: str,
    *,
    lang: str,
    duration_seconds: float | None,
    context: dict[str, Any] | None,
    api_key: str,
) -> str | None:
    try:
        prompt = _build_llm_prompt(place, lang=lang, duration_seconds=duration_seconds, context=context)
        payload = json.dumps({
            "model": "gpt-4o-mini",
            "max_tokens": 400,
            "messages": [{"role": "user", "content": prompt}],
        }).encode()
        req = urllib.request.Request(
            "https://api.openai.com/v1/chat/completions",
            data=payload,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=12) as resp:
            result = json.loads(resp.read().decode())
        choices = result.get("choices") or []
        if choices:
            return (choices[0].get("message") or {}).get("content", "").strip() or None
    except Exception:  # noqa: BLE001
        pass
    return None


# ---------------------------------------------------------------------------
# Template narration (offline, always available)
# ---------------------------------------------------------------------------

def _fallback(place: str, lang: str, duration_seconds: float | None) -> str:
    if lang.startswith("tr"):
        base = f"Çelebi. {place}. Cinematic uçuş başlıyor."
    elif lang.startswith("de"):
        base = f"Celebi. {place}. Cinematic-Flug startet."
    else:
        base = f"Celebi. {place}. Cinematic flight engaging."
    return _pad_to_duration(base, lang=lang, duration_seconds=duration_seconds)


def _pad_to_duration(text: str, *, lang: str, duration_seconds: float | None) -> str:
    """Repeat meaningful content to roughly fill *duration_seconds*."""
    if duration_seconds is None:
        return text
    wpm = _WPM.get(lang[:2], 130)
    target_words = max(5, int(duration_seconds * wpm / 60))
    words = text.split()
    while len(words) < target_words:
        words.extend(text.split())
    return " ".join(words[:target_words])


def _compose(b: dict[str, Any], *, lang: str, duration_seconds: float | None = None) -> str:
    name = (b.get("place") or "").split(",")[0].strip() or "the area"
    w = b.get("weather") or {}
    temp = w.get("temperature_c")
    wind = w.get("wind_kmh")
    fires = b.get("wildfires_nearby") or 0
    cams = b.get("cameras") or []
    # Wildfire hotspot context (from snap_wildfire payload forwarded in context)
    hotspot = b.get("hotspot")

    if lang.startswith("tr"):
        parts = [f"Çelebi {name} üstünde."]
        if temp is not None:
            parts.append(f"Sıcaklık {round(temp)} derece.")
        if wind is not None:
            parts.append(f"Rüzgâr {round(wind)} kilometre saat.")
        if hotspot:
            frp = hotspot.get("frp")
            parts.append(f"Aktif yangın tespit edildi.")
            if frp:
                parts.append(f"Yangın gücü {round(frp)} megawatt.")
        elif fires:
            parts.append(f"Yakında {fires} aktif termal nokta var.")
        if cams:
            parts.append(f"Canlı kamera: {cams[0]['name']}.")
        parts.append("Cinematic uçuş başlıyor.")

    elif lang.startswith("de"):
        parts = [f"Celebi über {name}."]
        if temp is not None:
            parts.append(f"Temperatur {round(temp)} Grad.")
        if wind is not None:
            parts.append(f"Wind {round(wind)} Kilometer pro Stunde.")
        if hotspot:
            frp = hotspot.get("frp")
            parts.append("Aktives Feuer erkannt.")
            if frp:
                parts.append(f"Brandleistung {round(frp)} Megawatt.")
        elif fires:
            parts.append(f"In der Nähe {fires} aktive Hitzepunkte.")
        if cams:
            parts.append(f"Live-Kamera: {cams[0]['name']}.")
        parts.append("Cinematic-Flug startet.")

    else:
        parts = [f"Celebi over {name}."]
        if temp is not None:
            parts.append(f"Temperature {round(temp)} degrees.")
        if wind is not None:
            parts.append(f"Wind {round(wind)} kilometres per hour.")
        if hotspot:
            frp = hotspot.get("frp")
            parts.append("Active fire detected.")
            if frp:
                parts.append(f"Fire radiative power {round(frp)} megawatts.")
        elif fires:
            parts.append(f"{fires} active thermal anomalies nearby.")
        if cams:
            parts.append(f"Live camera: {cams[0]['name']}.")
        parts.append("Cinematic flight engaging.")

    text = " ".join(parts)
    return _pad_to_duration(text, lang=lang, duration_seconds=duration_seconds)
