"""Narration text builder + TTS bytes.

The browser fetches ``/api/narration?q=<place>&auto=1`` (or with
explicit ``&text=...``) and mixes the resulting audio into MediaRecorder
via Web Audio. No ffmpeg merge needed — the recording lays the audio
track directly into the .mp4 container alongside H.264 video.

Narration length is calibrated to video duration when ``duration_seconds``
is given. The daily briefing includes weather details, news headlines,
nearby aircraft, fires, and earthquakes so every flight feels like a
real intelligence report.

If ANTHROPIC_API_KEY or OPENAI_API_KEY is set, the text is generated by
the matching LLM for richer copy; the template builder is used as fallback.
"""

from __future__ import annotations

import json
import os
import urllib.request
from typing import Any

from . import live as live_mod


# Turkish ~110 wpm, German/English ~130 wpm (conservative for TTS clarity)
_WPM = {"tr": 110, "de": 125, "en": 130}

# Default video duration when none specified — matches Pilot sparse preset
_DEFAULT_DURATION = 36.0


def auto_text_for(
    place: str,
    *,
    lang: str = "tr",
    duration_seconds: float | None = None,
    context: dict[str, Any] | None = None,
) -> str:
    dur = duration_seconds if duration_seconds is not None else _DEFAULT_DURATION

    # Fetch rich live bundle (news + aircraft for daily briefing)
    if context is None:
        try:
            context = live_mod.snapshot(
                place,
                marine=False,
                radius_km=50.0,
                with_news=True,
                with_aircraft=True,
            )
        except Exception:  # noqa: BLE001
            context = {}

    # 1. LLM narration (richer, context-aware)
    llm = _llm_narration(place, lang=lang, duration_seconds=dur, context=context)
    if llm:
        return llm

    # 2. Template narration (always works offline)
    return _compose(context, place=place, lang=lang, duration_seconds=dur)


# ---------------------------------------------------------------------------
# LLM narration — stdlib urllib only, no new pip dependency
# ---------------------------------------------------------------------------

def _llm_narration(
    place: str,
    *,
    lang: str,
    duration_seconds: float,
    context: dict[str, Any],
) -> str | None:
    api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if api_key:
        return _anthropic_narration(place, lang=lang, duration_seconds=duration_seconds, context=context, api_key=api_key)
    api_key = os.environ.get("OPENAI_API_KEY", "").strip()
    if api_key:
        return _openai_narration(place, lang=lang, duration_seconds=duration_seconds, context=context, api_key=api_key)
    return None


def _build_llm_prompt(
    place: str,
    *,
    lang: str,
    duration_seconds: float,
    context: dict[str, Any],
) -> str:
    lang_names = {"tr": "Turkish", "de": "German", "en": "English"}
    lang_name = lang_names.get(lang[:2], "English")
    wpm = _WPM.get(lang[:2], 130)
    target = int(duration_seconds * wpm / 60)
    length_instr = f"exactly {target} words (for a {int(duration_seconds)}-second video at {wpm} wpm)"

    lines: list[str] = []
    w = context.get("weather") or {}
    if w.get("temperature_c") is not None:
        lines.append(f"Temperature {w['temperature_c']}°C, feels like {w.get('feels_like_c', '?')}°C")
    if w.get("wind_kmh") is not None:
        lines.append(f"Wind {w['wind_kmh']} km/h from {w.get('wind_direction', '?')}")
    if w.get("humidity_pct") is not None:
        lines.append(f"Humidity {w['humidity_pct']}%")
    if w.get("description"):
        lines.append(f"Conditions: {w['description']}")

    fires = context.get("wildfires_nearby") or 0
    if fires:
        lines.append(f"{fires} active wildfire hotspots within 200 km")

    quakes = context.get("earthquakes_nearby") or 0
    if quakes:
        eq_list = context.get("earthquakes") or []
        if eq_list:
            biggest = max(eq_list, key=lambda q: q.get("magnitude") or 0)
            lines.append(f"{quakes} recent earthquakes, strongest M{biggest.get('magnitude', '?')} at {biggest.get('location', 'nearby')}")

    ac_list = context.get("aircraft") or []
    if ac_list:
        lines.append(f"{len(ac_list)} aircraft overhead — including {ac_list[0].get('callsign', 'unknown')}")

    news_list = context.get("news") or []
    for item in news_list[:2]:
        title = (item.get("title") or "").strip()
        if title:
            lines.append(f"News: {title[:80]}")

    cams = context.get("cameras") or []
    if cams:
        lines.append(f"Live camera available: {cams[0].get('name', '')}")

    hotspot = context.get("hotspot")
    if hotspot:
        lines.append(f"Active fire detected — FRP {hotspot.get('frp', '?')} MW")

    ctx_block = "\n".join(f"- {l}" for l in lines) if lines else ""

    return (
        f"You are the narrator for CelebiPlug, a cinematic drone system with a deep, confident male voice.\n"
        f"Write a drone narration in {lang_name} for: {place}.\n"
        f"Real-time intelligence:\n{ctx_block}\n\n"
        f"Length: {length_instr}.\n"
        f"Style: cinematic, authoritative, journalistic. Mention weather, any fires or quakes, aircraft, "
        f"news if relevant — like a daily intelligence briefing from above. "
        f"Begin with 'Çelebi' (the drone name). Flowing sentences, no bullet points. "
        f"Return ONLY the narration text."
    )


def _anthropic_narration(
    place: str,
    *,
    lang: str,
    duration_seconds: float,
    context: dict[str, Any],
    api_key: str,
) -> str | None:
    try:
        prompt = _build_llm_prompt(place, lang=lang, duration_seconds=duration_seconds, context=context)
        payload = json.dumps({
            "model": "claude-haiku-4-5-20251001",
            "max_tokens": 600,
            "messages": [{"role": "user", "content": prompt}],
        }).encode()
        req = urllib.request.Request(
            "https://api.anthropic.com/v1/messages",
            data=payload,
            headers={
                "Content-Type": "application/json",
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=12) as resp:
            result = json.loads(resp.read().decode())
        for block in result.get("content") or []:
            if block.get("type") == "text":
                return block["text"].strip()
    except Exception:  # noqa: BLE001
        pass
    return None


def _openai_narration(
    place: str,
    *,
    lang: str,
    duration_seconds: float,
    context: dict[str, Any],
    api_key: str,
) -> str | None:
    try:
        prompt = _build_llm_prompt(place, lang=lang, duration_seconds=duration_seconds, context=context)
        payload = json.dumps({
            "model": "gpt-4o-mini",
            "max_tokens": 600,
            "messages": [{"role": "user", "content": prompt}],
        }).encode()
        req = urllib.request.Request(
            "https://api.openai.com/v1/chat/completions",
            data=payload,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=12) as resp:
            result = json.loads(resp.read().decode())
        choices = result.get("choices") or []
        if choices:
            return ((choices[0].get("message") or {}).get("content") or "").strip() or None
    except Exception:  # noqa: BLE001
        pass
    return None


# ---------------------------------------------------------------------------
# Template narration — offline, always available
# ---------------------------------------------------------------------------

def _compose(
    b: dict[str, Any],
    *,
    place: str,
    lang: str,
    duration_seconds: float,
) -> str:
    name = (b.get("place") or place or "").split(",")[0].strip() or "the area"
    w = b.get("weather") or {}
    temp = w.get("temperature_c")
    feels = w.get("feels_like_c")
    wind = w.get("wind_kmh")
    wind_dir = w.get("wind_direction") or w.get("wind_dir")
    humidity = w.get("humidity_pct")
    desc = (w.get("description") or "").strip()
    fires = b.get("wildfires_nearby") or 0
    fire_list = b.get("wildfires") or []
    quakes = b.get("earthquakes_nearby") or 0
    quake_list = b.get("earthquakes") or []
    cams = b.get("cameras") or []
    news_list = b.get("news") or []
    ac_list = b.get("aircraft") or []
    hotspot = b.get("hotspot")

    if lang.startswith("tr"):
        parts = [f"Çelebi {name} üzerinde."]
        if desc:
            parts.append(f"Gökyüzü {desc.lower()}.")
        if temp is not None:
            t_str = f"Hava sıcaklığı {round(temp)} derece"
            if feels is not None and abs(feels - temp) > 1:
                t_str += f", hissedilen {round(feels)} derece"
            parts.append(t_str + ".")
        if wind is not None:
            w_str = f"Rüzgar saatte {round(wind)} kilometre"
            if wind_dir:
                w_str += f" {wind_dir} yönünden esiyor"
            parts.append(w_str + ".")
        if humidity is not None:
            parts.append(f"Nem oranı yüzde {round(humidity)}.")
        if hotspot:
            frp = hotspot.get("frp")
            parts.append(f"Bölgede aktif yangın noktası tespit edildi.")
            if frp:
                parts.append(f"Yangın radyatif gücü {round(frp)} megawatt.")
        elif fires:
            parts.append(f"İki yüz kilometre yarıçapında {fires} aktif termal nokta var.")
            if fire_list:
                parts.append("Yangın durumu izleniyor.")
        if quakes:
            parts.append(f"Son yirmi dört saatte bölgede {quakes} deprem kaydedildi.")
            if quake_list:
                biggest = max(quake_list, key=lambda q: q.get("magnitude") or 0)
                mag = biggest.get("magnitude")
                loc = (biggest.get("location") or "").split(",")[0]
                if mag:
                    parts.append(f"En büyüğü {'yaklaşık ' if mag else ''}{mag} büyüklüğünde{', ' + loc if loc else ''}.")
        if ac_list:
            parts.append(f"Şu an bölgede {len(ac_list)} uçak seyir halinde.")
            first = ac_list[0]
            cs = first.get("callsign")
            if cs:
                alt = first.get("baro_altitude_m")
                spd = first.get("speed_kmh")
                ac_str = f"{cs} uçuşu"
                if alt:
                    ac_str += f" {round(alt)} metre irtifada"
                if spd:
                    ac_str += f", saatte {round(spd)} kilometre hızla"
                parts.append(ac_str + " ilerliyor.")
        if news_list:
            top = (news_list[0].get("title") or "").strip()
            if top:
                parts.append(f"Gündemden: {top.rstrip('.')}.")
        if cams:
            parts.append(f"Bölgeye ait canlı kamera: {cams[0]['name']}.")
        parts.append("Çelebi sinematik uçuşunu sürdürüyor.")

    elif lang.startswith("de"):
        parts = [f"Celebi über {name}."]
        if desc:
            parts.append(f"Der Himmel zeigt sich {desc.lower()}.")
        if temp is not None:
            t_str = f"Die Lufttemperatur beträgt {round(temp)} Grad"
            if feels is not None and abs(feels - temp) > 1:
                t_str += f", gefühlt {round(feels)} Grad"
            parts.append(t_str + ".")
        if wind is not None:
            w_str = f"Wind {round(wind)} Kilometer pro Stunde"
            if wind_dir:
                w_str += f" aus {wind_dir}"
            parts.append(w_str + ".")
        if humidity is not None:
            parts.append(f"Luftfeuchtigkeit {round(humidity)} Prozent.")
        if hotspot:
            parts.append("Aktiver Brandherd in der Region erkannt.")
        elif fires:
            parts.append(f"{fires} aktive Wärmepunkte im Umkreis von 200 Kilometern.")
        if quakes:
            parts.append(f"{quakes} Erdbeben in den letzten 24 Stunden registriert.")
        if ac_list:
            parts.append(f"{len(ac_list)} Flugzeuge derzeit im Luftraum.")
        if news_list:
            top = (news_list[0].get("title") or "").strip()
            if top:
                parts.append(f"Aktuell: {top.rstrip('.')}.")
        if cams:
            parts.append(f"Live-Kamera: {cams[0]['name']}.")
        parts.append("Celebi setzt den cinematischen Flug fort.")

    else:
        parts = [f"Celebi over {name}."]
        if desc:
            parts.append(f"Skies are {desc.lower()}.")
        if temp is not None:
            t_str = f"Air temperature {round(temp)} degrees"
            if feels is not None and abs(feels - temp) > 1:
                t_str += f", feels like {round(feels)}"
            parts.append(t_str + ".")
        if wind is not None:
            w_str = f"Wind at {round(wind)} kilometres per hour"
            if wind_dir:
                w_str += f" from the {wind_dir}"
            parts.append(w_str + ".")
        if humidity is not None:
            parts.append(f"Humidity at {round(humidity)} percent.")
        if hotspot:
            frp = hotspot.get("frp")
            parts.append("Active fire hotspot detected in the area.")
            if frp:
                parts.append(f"Fire radiative power {round(frp)} megawatts.")
        elif fires:
            parts.append(f"{fires} active thermal anomalies within 200 kilometres.")
        if quakes:
            parts.append(f"{quakes} earthquakes recorded in the region over the last 24 hours.")
        if ac_list:
            parts.append(f"{len(ac_list)} aircraft currently in the airspace.")
            first = ac_list[0]
            cs = first.get("callsign")
            if cs:
                parts.append(f"{cs} is among them.")
        if news_list:
            top = (news_list[0].get("title") or "").strip()
            if top:
                parts.append(f"From the headlines: {top.rstrip('.')}.")
        if cams:
            parts.append(f"Live camera on the ground: {cams[0]['name']}.")
        parts.append("Celebi continues its cinematic flight.")

    text = " ".join(parts)
    return _pad_to_duration(text, lang=lang, duration_seconds=duration_seconds)


def _pad_to_duration(text: str, *, lang: str, duration_seconds: float) -> str:
    wpm = _WPM.get(lang[:2], 130)
    target_words = max(10, int(duration_seconds * wpm / 60))
    words = text.split()
    if len(words) >= target_words:
        return " ".join(words[:target_words])
    # Pad by repeating the tail of the text (avoids robotic repetition)
    tail = " ".join(words[-6:]) if len(words) >= 6 else text
    while len(words) < target_words:
        words.extend(tail.split())
    return " ".join(words[:target_words])
